apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: d44dk91i3-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:eb3ccacf73afd149f35ba04af6b460b0537032b9@sha256:66aa8487053e03a85f2b1d25b1a6ff53afeb2e094934cf19f2d277b5f42c3016
          name: container-image
